### ISSUE TITLE
NPM Install Issue

### ISSUE THREAD

**Issue by mackenly** [jschlesser/authjs-sveltkit-cloudflare-pages#3]
Hi @jschlesser! Nice project! When following onlong with the instructions in the README (both locally and in a codespace) I received the following error when I ```npm install``` the dependences. This is fixed by deleting the ```package-lock.json```. Is this an artifact from using pnpm?
```
npm ERR! code ECONNREFUSED
npm ERR! syscall connect
npm ERR! errno ECONNREFUSED
npm ERR! FetchError: request to http://localhost:4873/@auth/sveltekit/-/sveltekit-0.3.0.tgz failed, reason: connect ECONNREFUSED ::1:4873
npm ERR!     at ClientRequest.<anonymous> (/usr/local/share/nvm/versions/node/v19.7.0/lib/node_modules/npm/node_modules/minipass-fetch/lib/index.js:130:14)
npm ERR!     at ClientRequest.emit (node:events:512:28)
npm ERR!     at Socket.socketErrorListener (node:_http_client:496:9)
npm ERR!     at Socket.emit (node:events:524:35)
npm ERR!     at emitErrorNT (node:internal/streams/destroy:151:8)
npm ERR!     at emitErrorCloseNT (node:internal/streams/destroy:116:3)
npm ERR!     at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
npm ERR!  FetchError: request to http://localhost:4873/@auth/sveltekit/-/sveltekit-0.3.0.tgz failed, reason: connect ECONNREFUSED ::1:4873
npm ERR!     at ClientRequest.<anonymous> (/usr/local/share/nvm/versions/node/v19.7.0/lib/node_modules/npm/node_modules/minipass-fetch/lib/index.js:130:14)
npm ERR!     at ClientRequest.emit (node:events:512:28)
npm ERR!     at Socket.socketErrorListener (node:_http_client:496:9)
npm ERR!     at Socket.emit (node:events:524:35)
npm ERR!     at emitErrorNT (node:internal/streams/destroy:151:8)
npm ERR!     at emitErrorCloseNT (node:internal/streams/destroy:116:3)
npm ERR!     at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
npm ERR!   code: 'ECONNREFUSED',
npm ERR!   errno: 'ECONNREFUSED',
npm ERR!   syscall: 'connect',
npm ERR!   address: '::1',
npm ERR!   port: 4873,
npm ERR!   type: 'system'
npm ERR! }
npm ERR! 
npm ERR! If you are behind a proxy, please make sure that the
npm ERR! 'proxy' config is set properly.  See: 'npm help config'
```

**Comment by mackenly** [comment]
Additionally should ```npm build``` and ```npm wrangle``` in the README be replaced with ```npm run build``` and ```npm run wrangle``` as well?

**Comment by jschlesser** [comment]
Thanks,
I have pushed up some fixes, im in the process of verifying them in a codespace right now.   I realize that I have misspelled the repo name and id like to fix that up from authjs-sveltkit-cloudflare-pages -> authjs-sveltkit-cloudflare-pages .  I'll need to go fix some links in the PR and issue on the next-auth repo when I do that.    I'll make that change after you tell me you can make it through the instructions.

**Comment by jschlesser** [comment]
@mackenly , I gave it a good shot on the codespace.  I configured a new GitHub OAuth App and set the environment variables.  I got the app to boot and and accessed the index page of the app but the signing doesn't work on a codespace when being proxied to my local browser as it sees the host as localhost during an oauth redirect.  However, it's enough for me to know that it should now work fine on your local machine.   Please give it another try.  Thanks.

**Comment by mackenly** [comment]
@jschlesser  Just tested it locally and it seems to work perfectly! 🔥

The ```npm install``` issue is also fixed. Yeah, Wrangler in codespaces is bit weird.
